# Generated by Django 5.0 on 2023-12-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultpractice',
            name='date',
            field=models.DateField(),
        ),
    ]
