# Generated by Django 5.0 on 2024-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_resultpractice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloquestion',
            name='solution_here',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
