# Generated by Django 5.0 on 2024-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_solution_here_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution_here',
            field=models.ImageField(blank=True, default=1, upload_to='actual_quiz_photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soloquestion',
            name='solution_here',
            field=models.ImageField(blank=True, default=1, upload_to='actual_quiz_photo/'),
            preserve_default=False,
        ),
    ]
